### ISSUE TITLE
cuenta de amazon

### ISSUE THREAD

**Issue by franciscop1s3** [UG-Cloud-Computing-2016-Semester1/Temario#12]
al momento de crear nueva cuenta en amazon elijo la de empresa o cuenta personal? o.O

**Comment by franciscop1s3** [comment]
a y tambien como pongo el numero de telefono es que recuerdo que habia dicho algo de poner 01 o algo asi

**Comment by JuanCrg90** [comment]
Personal @franciscop1s3 

les dije que le agregaran un 1 entre el +52 y la clave de lada

+521462XXXXXX

**Comment by franciscop1s3** [comment]
sale gracias profe
